//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : Features.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//


public enum Features {
	None,
	SuperStacks
}
