//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : Symbols.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//


public enum Symbols {
	None,
	WD1,
	HP1,
	HP2,
	HP3,
	HP4,
	HP5,
    End
}
