//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : AudioManager.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//

using UnityEngine;
using System.Collections;

public class AudioManager 
{
	public AudioClip aRollups ;
	public object aCelebrationRollup ;
	public void FindAndSetRollups()
    {

	}
	public void PlayRollup(int iRollup)
    {

	}
	public void SetSequenceClips(AudioClip[] Sequence)
    {

	}
	public void PlaySequenceClips()
    {

	}
	public void InterruptAudio()
    {

	}
	public void InterruptAndReplaceAudio(AudioClip Replacementclip)
    {

	}
}
