//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : FeaturesManager.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//


public class FeaturesManager {
	public Features feaActivatedFeatures ;
	public void AnalyzeWinForFeatureActivation(Reel[] EndingCombination){
	}
	public void ActivateFeature(string Feature){
	}
}
