//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : TransitionsManager.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//


public class TransitionsManager 
{

    //Unity Functions
    void OnEnable()
    {
        StateManager.ActivateSwitchState += SwitchState;
    }

    void ZeroValues()
    {
        StateManager.ActivateSwitchState -= SwitchState;
    }

    //Transition Functions
    public void SwitchState(States State)
    {
        //Play State Transition Switching(State);
    }
}
