//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : GaffManager.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//


using System.Collections;
using System.Collections.Generic;

public class GaffManager 
{
	public void DrawGaffOnScreen()
    {

	}

	public void SelectStops()
    {

	}

	public void AutoPlay()
    {

	}

	public void SetReels(Reel[] rReelConfiguration)
    {

	}

	public void SetMultiSpinReels(List<Reel[]> rReelConfiguration)
    {

	}
}
