//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : MatrixTypes.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//

//Had to add m infront of Matrix Types due to identifier error
public enum MatrixTypes
{
	None,
	m3x5,
	m3x6,
	m3x4x5x4x3,
	m4x5,
	m4x6
}
