//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : PlayerInformation.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//


public class PlayerInformation 
{
	public string sUsername ;

}
