//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : Symbols.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//


public enum Symbols {
	None = -1,
	MA01,
	MA02,
	MA03,
	MA04,
	MA05,
	MI01,
	MI02,
	MI03,
	MI04,
	MI05,
    End
}
