//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Slot Engine
//  @ File Name : WinConditions.cs
//  @ Date : 5/7/2014
//  @ Author : Evan McCall
//
//


public class WinConditions {
	public void CheckMatrix(Reel[] rMatrix){
	}
}
